name: Code Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Code lint

    steps:
      - name: â¬‡ Git checkout
        uses: actions/checkout@v4

      - name: ğŸ’¾ Install modules
        run: npm ci

      - name: ğŸ” ESLint validation
        run: npx eslint --ignore-path .gitignore . --max-warnings 0
